version: '3'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
<<<<<<< HEAD
    environment:
      - MONGO_URI=mongodb://mongo:27018/
=======
    env_file:
      - .env
>>>>>>> 07135de9b5258eebac02692832b910ba23c35eb0

  frontend:
    build: ./Frontend
    ports:
<<<<<<< HEAD
      - "3000:80"
=======
      - "80:80"
    env_file:
      - .env
>>>>>>> 07135de9b5258eebac02692832b910ba23c35eb0

  mongo:
    image: mongo
    ports:
      - "27018:27017"
