version: '3'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  frontend:
    build: ./Frontend
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
