version: '3'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    env_file:
      - .env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
